services:
  - type: web
    name: variety-adventure-v1
    runtime: python
    buildCommand: |
      pip install poetry
      poetry install --no-root
    startCommand: streamlit run app.py --server.port $PORT